@startuml
'https://plantuml.com/class-diagram
scale 2
skinparam classAttributeIconSize 0
skinparam classFontStyle Bold
skinparam defaultFontSize 15
skinparam style strictuml
hide empty members
left to right direction

' classe dé
class Des
'classe donjon
class Donjon

'classes entité
abstract class Entite
class Monstre --|> Entite

@enduml
